# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pass.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import random
import string
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 766)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 1041, 701))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(6)
        self.frame.setObjectName("frame")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 1001, 661))
        font = QtGui.QFont()
        font.setFamily("Lohit Devanagari")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 11, 981, 581))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 10, 601, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.VLine)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setLineWidth(4)
        self.label.setMidLineWidth(0)
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.tab)
        self.checkBox.setGeometry(QtCore.QRect(50, 0, 731, 71))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setObjectName("checkBox")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(0, 100, 661, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(4)
        self.label_2.setMidLineWidth(0)
        self.label_2.setObjectName("label_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_2.setGeometry(QtCore.QRect(150, 90, 661, 71))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(0, 190, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(4)
        self.label_3.setMidLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_3.setGeometry(QtCore.QRect(180, 180, 521, 71))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_3.setObjectName("checkBox_3")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(0, 280, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setLineWidth(4)
        self.label_7.setMidLineWidth(0)
        self.label_7.setObjectName("label_7")
        self.checkBox_7 = QtWidgets.QCheckBox(self.tab)
        self.checkBox_7.setGeometry(QtCore.QRect(-30, 270, 521, 71))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(19)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        font.setKerning(True)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(0, 370, 761, 41))
        font = QtGui.QFont()
        font.setFamily("Purisa")
        font.setPointSize(19)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setLineWidth(4)
        self.label_8.setMidLineWidth(0)
        self.label_8.setObjectName("label_8")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(460, 375, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Lohit Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.spinBox.setFont(font)
        self.spinBox.setMaximum(101)
        self.spinBox.setSingleStep(1)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(430, 530, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Lohit Devanagari")
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 440, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setLineWidth(4)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(340, 440, 241, 61))
        self.lineEdit.setObjectName("lineEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(0, 70, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setLineWidth(4)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 70, 221, 61))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(10, 260, 971, 21))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 221, 41))
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setLineWidth(5)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 288, 311, 41))
        self.label_9.setFrameShape(QtWidgets.QFrame.Box)
        self.label_9.setLineWidth(5)
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(90, 149, 161, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser.setGeometry(QtCore.QRect(575, 10, 411, 241))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 340, 971, 251))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 280, 131, 51))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(560, 280, 131, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 26))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        self.checkBox.clicked.connect(self.hrof_bozorg)
        self.checkBox_2.clicked.connect(self.hrof_kochik)
        self.checkBox_3.clicked.connect(self.adad)
        self.checkBox_7.clicked.connect(self.syntax)
        self.pushButton.clicked.connect(self.pass_maker)
        self.pushButton.clicked.connect(self.save_pass)
        self.pushButton_2.clicked.connect(self.serch_by_nsme)
        self.pushButton_3.clicked.connect(self.serch)
        self.pushButton_4.clicked.connect(self.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def hrof_bozorg(self):
        list_hrof = []
        hrofbozorg = string.ascii_uppercase
        for i in range (0,240):
            list_hrof.append(random.choice(hrofbozorg))
        x = "".join(list_hrof)
        return x
    def hrof_kochik(self):
        list_hrof = []
        hrofkochik = string.ascii_lowercase
        for i in range (0,240):
            list_hrof.append(random.choice(hrofkochik))
        x = "".join(list_hrof)
        return x
    def adad(self):
        list_adad = []
        string_adad = []
        for i in range (0,100):
            list_adad.append(random.randint(0,9))
        for har_adad in list_adad:
            har_adad = str(har_adad)
            string_adad.append(har_adad)
        x = "".join(string_adad)
        return x
    def syntax(self):
        syntax_list = []
        list_syntax = ["~","!","@","#","$","%","&","_","-","*",","]
        for i in range(0,100):
            syntax_list.append(random.choice(list_syntax))
        x = "".join(syntax_list)
        return x
    def pass_maker(self):
        if self.checkBox.isChecked():
            x1 = self.hrof_bozorg()
        else :
            x1 = ""
        if self.checkBox_2.isChecked():
            x2 = self.hrof_kochik()
        else :
            x2 = ""
        if self.checkBox_3.isChecked():
            x3 = self.adad()
        else :
            x3 = ""
        if self.checkBox_7.isChecked():
            x4 = self.syntax()
        else :
            x4 = ""
        string_pass = x1 + x2 + x3 + x4
        password = ""
        while len(password) != self.spinBox.value() :
            password += random.choice(string_pass)
        return password   
    def save_pass(self):
        pas = self.pass_maker()
        pass_name = self.lineEdit.text()
        f = open("passwordfile.txt","a")
        f.write("%s = %s \n" % ( pass_name , pas ))
        f.close()
    def serch(self):
        f = open("passwordfile.txt",'r')
        self.textBrowser_2.append(f.read())
    def serch_by_nsme(self):
        name = self.lineEdit_2.text()
        f = open("passwordfile.txt","r")
        text = f.read()
        text = text.strip().split()
        if name in text :
            n = text.index(name)
            n += 2
            pas = text[n]
            self.textBrowser.append(pas)
        else :
            self.textBrowser.append("There is no passworld with this name.")
        f.close()
    

    def hide(self):
        self.textBrowser_2.clear()
    


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "password maker"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Lohit Devanagari\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Appliction instructions :</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">    <span style=\" font-weight:400; font-style:italic;\">1 - In password option tab chose what options do you want for your pass</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400; font-style:italic;\">    2 - Chose your password Length</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400; font-style:italic;\">    3 - Give a name to your password</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400; font-style:italic;\">    4 - Clicked the button and the app will make your password</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400; font-style:italic;\">    5 - In your passwords you can see your pervios password</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "HOME"))
        self.label.setText(_translate("MainWindow", "Upper case letters"))
        self.checkBox.setText(_translate("MainWindow", "Pick a random Upper case letters from (A,Z)"))
        self.label_2.setText(_translate("MainWindow", "Lower case letters"))
        self.checkBox_2.setText(_translate("MainWindow", "pick a random Lower case letters from (a,z)"))
        self.label_3.setText(_translate("MainWindow", "Numbers"))
        self.checkBox_3.setText(_translate("MainWindow", "Pick a random Number from (0,9)"))
        self.label_7.setText(_translate("MainWindow", "Syntax"))
        self.checkBox_7.setText(_translate("MainWindow", "Pick a random Syntax"))
        self.label_8.setText(_translate("MainWindow", "Your passworld length"))
        self.pushButton.setText(_translate("MainWindow", "create"))
        self.label_4.setText(_translate("MainWindow", "Password name : "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Password option"))
        self.label_5.setText(_translate("MainWindow", "Passworld name : "))
        self.label_6.setText(_translate("MainWindow", "Serch by name"))
        self.label_9.setText(_translate("MainWindow", "All of your passwords"))
        self.pushButton_2.setText(_translate("MainWindow", "Serch"))
        self.pushButton_3.setText(_translate("MainWindow", "SHOW"))
        self.pushButton_4.setText(_translate("MainWindow", "HIDE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Your passwords"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
